In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.3]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10, 11, 12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.3

## Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[0, 3, 4, 3, 0],
       [8, 4, 9, 7, 0],
       [5, 3, 5, 2, 0]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5,3))
random_array_2 

array([[0.0028508 , 0.77750725, 0.14318129],
       [0.58325769, 0.07673678, 0.75812101],
       [0.45821485, 0.30087992, 0.94825628],
       [0.59013237, 0.81861805, 0.41371935],
       [0.34489847, 0.10408929, 0.58723053]])

In [33]:
random_array_2.shape

(5, 3)

In [34]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.57891849, 0.21442879, 0.11151033],
       [0.20455925, 0.80556821, 0.418923  ],
       [0.29578712, 0.66450422, 0.35419121],
       [0.14400431, 0.33163461, 0.88032252],
       [0.01713545, 0.72600312, 0.03870397]])

In [41]:
# Pseudo-random numbers to get the same random number
np.random.seed(seed=2)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

In [44]:
np.random.seed(seed=5)
random_array_5 = np.random.random((5,3))
random_array_5 

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

In [45]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.27408646, 0.41423502, 0.29607993],
       [0.62878791, 0.57983781, 0.5999292 ],
       [0.26581912, 0.28468588, 0.25358821],
       [0.32756395, 0.1441643 , 0.16561286],
       [0.96393053, 0.96022672, 0.18841466]])

## 3. Viewing arrays and metrices

In [46]:
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.3]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [48]:
a1[0]

1

In [50]:
a2.shape

(2, 3)

In [49]:
a2[0]

array([1. , 2. , 3.3])

In [51]:
a3.shape

(2, 3, 3)

In [52]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a2[1]

array([4. , 5. , 6.3])

In [55]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [56]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[9, 3, 3, 2, 1],
         [5, 7, 4, 3, 1],
         [7, 3, 1, 9, 5],
         [7, 0, 9, 6, 0]],

        [[5, 2, 8, 6, 8],
         [0, 5, 2, 0, 7],
         [7, 6, 0, 0, 8],
         [5, 5, 9, 6, 4]],

        [[5, 2, 8, 8, 1],
         [6, 3, 4, 1, 8],
         [0, 2, 2, 4, 1],
         [6, 3, 4, 3, 1]]],


       [[[4, 2, 3, 4, 9],
         [4, 0, 6, 6, 9],
         [2, 9, 3, 0, 8],
         [8, 9, 7, 4, 8]],

        [[6, 8, 0, 5, 3],
         [4, 0, 2, 2, 1],
         [1, 7, 1, 7, 2],
         [6, 3, 6, 8, 0]],

        [[9, 1, 9, 0, 8],
         [7, 7, 9, 4, 1],
         [4, 2, 1, 7, 5],
         [4, 2, 2, 1, 2]]]])

In [59]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [61]:
# Get the first 4 number of the inner most array
a4[:, :, :, :4]

array([[[[9, 3, 3, 2],
         [5, 7, 4, 3],
         [7, 3, 1, 9],
         [7, 0, 9, 6]],

        [[5, 2, 8, 6],
         [0, 5, 2, 0],
         [7, 6, 0, 0],
         [5, 5, 9, 6]],

        [[5, 2, 8, 8],
         [6, 3, 4, 1],
         [0, 2, 2, 4],
         [6, 3, 4, 3]]],


       [[[4, 2, 3, 4],
         [4, 0, 6, 6],
         [2, 9, 3, 0],
         [8, 9, 7, 4]],

        [[6, 8, 0, 5],
         [4, 0, 2, 2],
         [1, 7, 1, 7],
         [6, 3, 6, 8]],

        [[9, 1, 9, 0],
         [7, 7, 9, 4],
         [4, 2, 1, 7],
         [4, 2, 2, 1]]]])

## 4. Manipulating & Comparing arrays

### Arithmetic

In [62]:
a1

array([1, 2, 3])

In [63]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [64]:
a1 + ones

array([2., 3., 4.])

In [65]:
a1 - ones

array([0., 1., 2.])

In [66]:
a1*ones

array([1., 2., 3.])

In [67]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [68]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 18.9]])

In [70]:
# How can you reshape a2 to be compatible with a3?
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [71]:
a1 / ones

array([1., 2., 3.])

In [72]:
# Floor division removes the decimals (rounds down)
a2 // a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 39.69]])

In [74]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 39.69]])

In [75]:
np.add(a1, ones)

array([2., 3., 4.])

In [76]:
a1 %2

array([1, 0, 1], dtype=int32)

In [77]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.3]])

In [78]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [79]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation


Aggregation = performing the same operation on a number of things

In [80]:
listy_list = [1,2,3]
type(listy_list)

list

In [81]:
sum(listy_list)

6

In [82]:
sum(a1)

6

In [83]:
np.sum(a1)

6

### Use Python's method (sum()) on Python datatypes and use NumPy's method on Numpy arrays (np.sum())

In [84]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [86]:
massive_array[:10]

array([0.34167404, 0.84414   , 0.62830878, 0.20018449, 0.38096354,
       0.52351223, 0.67537613, 0.28125893, 0.7534345 , 0.70156022])

In [87]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()
# Numpy is faster

7.06 ms ± 96.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
41.6 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [88]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [89]:
np.mean(a2)

3.6

In [90]:
np.max(a2)

6.3

In [91]:
np.min(a2)

1.0

In [92]:
# Standard Deviation = a measure of how spred out a group of numbers is from the mean
np.std(a2)

1.7710637105046974

In [93]:
# Compute the variance along the specified axis, measure of the average degree to which each number is differnet
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.1366666666666663

In [95]:
standard_dev = np.sqrt(np.var(a2))
standard_dev

1.7710637105046974